const photos = {
  terralith: 'https://cdn.modrinth.com/data/8oi3bsk5/images/4957da7c3da1386fb12b76001a2321be7b2ff9bc_350.webp',
  wildlife: 'https://cdn.modrinth.com/data/F8BQNPWX/images/b920e0bcf6ceb1dbd5bf706f41a87b8f8a1814a4_350.webp',
  cooking: 'https://cdn.modrinth.com/data/7vxePowz/images/1c57e4c64a97a8eb13bc05a916cc607e2ff65658_350.webp',
  automation: 'https://cdn.modrinth.com/data/4sYI62kA/images/4bc6fada20efbb18536ae2934dc010380bfd38e0_350.webp',
  building: 'https://cdn.modrinth.com/data/pJmCFF0p/images/1fc28fcef052332a89cc56db64c097bd93d31f54_350.webp',
  dungeon: 'https://cdn.modrinth.com/data/o1C1Dkj5/images/1a3ee86e7269bd3703d8ece03cf897b70d2188df_350.webp',
};

const guides = [
  { n: '01', title: 'A living frontier', image: photos.wildlife, mods: 'Naturalist', source: 'https://modrinth.com/mod/naturalist', intro: 'Observation comes before extraction. Naturalist fills biomes with distinct species, variants, and atmosphere, so animals are more than early-game loot.', steps: ['Watch before attacking: a herd or pack can change an encounter.', 'Bring food home deliberately; animals are not just early-game loot.', 'Let the biome inform the base: water, cover, grazing room, and sightlines all matter.'] },
  { n: '02', title: 'Travel earns its views', image: photos.terralith, mods: 'Terralith + Tectonic + Gliding', source: 'https://modrinth.com/mod/terralith', intro: 'Terralith supplies the places; Tectonic makes the land consequential. Gliding turns a high route, a tower, or a cliff into an actual traversal decision.', steps: ['Do not claim a permanent house on day one. Find water, a defensible approach, and a promising route outward.', 'Make landmark towers and signposted junctions before fast travel exists.', 'Save gliding for planned expeditions: high ground is infrastructure.'] },
  { n: '03', title: 'Food is a project', image: photos.cooking, mods: "Farmer's Delight Refabricated + NutritionZ", source: 'https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated', intro: 'Bread is no longer the whole economy. NutritionZ asks for five nutrients, while Farmer’s Delight gives the kitchen enough texture to answer with meals instead of a spreadsheet.', steps: ['Plant a small mixed plot, not a giant wheat monoculture.', 'Make a cutting board and cooking pot once shelter is secure.', 'Use JEI to find meals that solve a missing nutrient; rotate ingredients.'] },
  { n: '04', title: 'A base should answer back', image: photos.dungeon, mods: "Zombie Awareness + YUNG's Better Dungeons", source: 'https://modrinth.com/mod/zombie-awareness', intro: 'Nights are meant to have teeth. Zombies respond to sound, blood scent, and light; dungeons are real expeditions. A base earns its walls.', steps: ['Make the perimeter visible from inside: light approaches and keep one door you can defend.', 'Use height, moats, fences, and controlled entrances—not just a ring of torches.', 'Treat a dungeon as a trip: food, water, exit route, and a turn-back point.'] },
  { n: '05', title: 'Make a place, not a box', image: photos.building, mods: 'Supplementaries + Handcrafted', source: 'https://modrinth.com/mod/supplementaries', intro: 'These are the settlement mods. Handcrafted gives rooms a purpose; Supplementaries supplies jars, signposts, ropes, lights, planters, faucets, and small useful mechanisms.', steps: ['Give the base a readable plan: kitchen, stores, workshop, lookout, bedrooms.', 'Use signs and path markers as shared memory for two players.', 'Build visible logistics first; good facades follow naturally.'] },
  { n: '06', title: 'Graduate from chores', image: photos.automation, mods: "Tom's Storage + CC: Tweaked + Oritech", source: 'https://tweaked.cc/module/turtle.html', intro: 'Start by making your stuff findable, then automate one annoying repeated job. Oritech is machinery and processing; CC: Tweaked is programmable computers and turtles.', steps: ['Build one visible Tom’s Storage network before adding more chests.', 'Give the first turtle a boring, trustworthy job: tree rows, a guarded quarry, or item transfer.', 'Use Oritech for a bottleneck—not as a second full-time job.'] },
];

const modRows = [
  ['World', 'Terralith', 'New biomes and structures made from vanilla blocks.'], ['World', 'Tectonic', 'Bigger terrain shapes; cliffs and basins become routes.'],
  ['Ecology', 'Naturalist', '47 animals, variants, and biome-specific atmosphere.'],
  ['Survival', 'NutritionZ', 'Five-nutrient diet; meal variety has a reason.'], ['Survival', "Farmer's Delight", 'Farming, cutting, cooking, and meals.'], ['Survival', 'Zombie Awareness', 'Threats notice blood, sound, and light.'],
  ['Explore', 'Gliding', 'A simple glider makes height and routes valuable.'], ['Explore', "YUNG's Better Dungeons", 'Dungeons redesigned as proper trips.'],
  ['Settle', 'Supplementaries', 'Useful small objects, light automation, and character.'], ['Settle', 'Handcrafted', 'Furniture and architectural pieces for lived-in rooms.'], ['Carry', "Traveler's Backpack", 'Upgradeable inventory, sleeping bag, and fluid tanks.'],
  ['Automate', "Tom's Simple Storage", 'One searchable, connected storage system.'], ['Automate', 'CC: Tweaked', 'Lua computers, turtles, modems, and programmable tools.'], ['Automate', 'Oritech', 'Machines, power, processing, and high-end equipment.'],
];

export default function Home() {
  return <main>
    <nav className="nav" aria-label="Primary navigation"><a className="brand" href="#top"><span>✦</span> OPEN-AIR SETTLEMENT</a><div className="navlinks"><a href="#loop">Play loop</a><a href="#mods">Mod index</a><a href="#setup">Setup</a></div></nav>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">REFERENCE GUIDE / FABRIC 1.21.1 / TWO PLAYERS</p><h1>Open-Air<br /><em>Settlement.</em></h1><p className="lede">A practical reference for the shared survival pack: installed systems, early-game priorities, multiplayer compatibility, and optional visual settings.</p><div className="hero-actions"><a className="button primary" href="#loop">First-week checklist <span>↓</span></a><a className="button quiet" href="#setup">Install &amp; join</a></div></div><div className="hero-images" aria-label="Scenes from included mods"><img className="hero-main" src={photos.terralith} alt="Terralith terrain" /><img className="hero-small top" src={photos.wildlife} alt="Naturalist wildlife" /><img className="hero-small bottom" src={photos.automation} alt="Oritech machinery" /><div className="image-caption">Fabric 1.21.1<br />Pack version 1.0.4</div></div></section>
    <section className="manifesto"><p><strong>Scope:</strong> this is a compact explanation of what is installed and how to use it. It is not a complete recipe guide; use JEI in-game for recipes and item uses.</p></section>
    <section className="week" id="loop"><div className="section-heading"><p className="eyebrow">FIRST-WEEK CHECKLIST</p><h2>Useful early priorities</h2></div><div className="week-grid"><article><span>DAY 1</span><h3>Choose a site</h3><p>Check water, food variety, visibility, and more than one route out before treating a place as permanent.</p></article><article><span>DAYS 2–3</span><h3>Secure night access</h3><p>Light approaches, make one defensible entrance, and maintain sightlines around the base.</p></article><article><span>DAYS 4–5</span><h3>Start food variety</h3><p>Plant several crops and cook mixed meals. NutritionZ tracks nutrients rather than calories alone.</p></article><article><span>DAYS 6–7</span><h3>Divide work deliberately</h3><p>Split surveying, farming, fortification, storage, or building so the first base has a clear purpose.</p></article></div></section>
    <section className="guide" aria-label="The field guide">{guides.map((guide) => <article className="guide-card" key={guide.n}><div className="card-art"><img src={guide.image} alt="" /><span>{guide.n}</span></div><div className="card-copy"><p className="eyebrow">{guide.mods}</p><h2>{guide.title}</h2><p>{guide.intro}</p><ol>{guide.steps.map((step) => <li key={step}>{step}</li>)}</ol><a href={guide.source} target="_blank" rel="noreferrer">Open the reference <span>↗</span></a></div></article>)}</section>
    <section className="mod-index" id="mods"><div className="section-heading"><p className="eyebrow">WHAT IS IN THE PACK</p><h2>The useful map, not the phone book</h2><p>The gameplay-facing mods are below. Fabric API, Moonlight, Architectury, Lithium, Noisium, FerriteCore, ModernFix, and other supporting libraries are there to make the pack run; they do not need your attention in play.</p></div><div className="mod-table">{modRows.map(([kind, name, description]) => <div className="mod-row" key={name}><span>{kind}</span><strong>{name}</strong><p>{description}</p></div>)}</div></section>
    <section className="setup" id="setup"><div><p className="eyebrow">INSTALLATION &amp; MULTIPLAYER</p><h2>Compatibility requirements</h2></div><div className="setup-list"><article><span>01</span><h3>Use the 1.0.4 pack</h3><p>Import the shared CurseForge zip, use Java 21, and launch Open-Air Settlement. Gameplay mods must match the server; client-only visual mods may differ.</p></article><article><span>02</span><h3>Connect on LAN</h3><p>Use the host computer’s current local IP address and port 25565. If the server is absent from the LAN list, add it once with Direct Connection.</p></article><article><span>03</span><h3>Keep automation inspectable</h3><p>Label turtle inputs and outputs, provide a stop switch for unattended processes, and document any system that consumes shared resources.</p></article></div></section>
    <section className="references"><p className="eyebrow">SOURCE SHELF</p><div className="reference-links"><a href="https://modrinth.com/mod/naturalist" target="_blank" rel="noreferrer">Naturalist</a><a href="https://modrinth.com/mod/terralith" target="_blank" rel="noreferrer">Terralith</a><a href="https://modrinth.com/mod/tectonic" target="_blank" rel="noreferrer">Tectonic</a><a href="https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated" target="_blank" rel="noreferrer">Farmer&apos;s Delight Refabricated</a><a href="https://tweaked.cc/module/turtle.html" target="_blank" rel="noreferrer">CC: Tweaked turtles</a><a href="https://www.curseforge.com/minecraft/mc-mods/travelers-backpack" target="_blank" rel="noreferrer">Traveler&apos;s Backpack</a><a href="https://modrinth.com/mod/oritech" target="_blank" rel="noreferrer">Oritech</a></div></section>
    <footer>OPEN-AIR SETTLEMENT <span>•</span> PACK REFERENCE / VERSION 1.0.4</footer>
  </main>;
}
