const photos = {
  terralith: 'https://cdn.modrinth.com/data/8oi3bsk5/images/4957da7c3da1386fb12b76001a2321be7b2ff9bc_350.webp',
  wildlife: 'https://cdn.modrinth.com/data/F8BQNPWX/images/b920e0bcf6ceb1dbd5bf706f41a87b8f8a1814a4_350.webp',
  cooking: 'https://cdn.modrinth.com/data/7vxePowz/images/1c57e4c64a97a8eb13bc05a916cc607e2ff65658_350.webp',
  automation: 'https://cdn.modrinth.com/data/4sYI62kA/images/4bc6fada20efbb18536ae2934dc010380bfd38e0_350.webp',
  building: 'https://cdn.modrinth.com/data/pJmCFF0p/images/1fc28fcef052332a89cc56db64c097bd93d31f54_350.webp',
  dungeon: 'https://cdn.modrinth.com/data/o1C1Dkj5/images/1a3ee86e7269bd3703d8ece03cf897b70d2188df_350.webp',
};

const guides = [
  { n: '01', title: 'Use the tools before the web', image: photos.building, mods: 'JEI + AppleSkin + Mod Menu + Xaero', source: 'https://modrinth.com/mod/jei', intro: 'This pack assumes that recipes are looked up in-game. JEI is the index; the guide is for decisions and priorities, not for memorising recipes.', steps: ['Hover an item in your inventory or JEI: press R for recipes and U for uses. Search an item name, or use @ followed by a mod name when the list is noisy.', 'If a key conflicts, open Options → Controls. Mod Menu is the place to inspect a mod’s settings; do not edit files just to answer a normal gameplay question.', 'Use the map as a record of routes, landmarks, farms, and danger—not as a reason to stop exploring.', 'Traveler’s Backpack is portable storage, a sleeping bag, and later a fluid carrier. It is convenience, not a replacement for a base.'] },
  { n: '02', title: 'Make food a system', image: photos.cooking, mods: "NutritionZ + Farmer's Delight Refabricated", source: 'https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated', intro: 'Food is the first self-sufficiency milestone. The goal is not a perfect kitchen; it is a small farm that can feed both players without reducing the world to bread.', steps: ['Plant several crop types and keep a few animal sources nearby. A mixed plot is more useful than a giant wheat field.', 'Use the NutritionZ display to notice which nutrients are falling behind, then ask JEI which meals contain them.', 'Farmer’s Delight has three useful ideas: ingredients can be portioned on the Cutting Board, meals are assembled in the Cooking Pot, and better food is worth preparing rather than merely hoarding.', 'Keep an emergency chest of simple foods. The kitchen should make expeditions possible, not make leaving home impossible.'] },
  { n: '03', title: 'Build for the night you actually have', image: photos.dungeon, mods: 'Zombie Awareness + YUNG’s Better Dungeons', source: 'https://modrinth.com/mod/zombie-awareness', intro: 'Zombie Awareness changes the question from “is the base lit?” to “what does the base reveal, emit, and leave exposed?”', steps: ['Blood, mining and building sounds, doors, containers, and other events can attract enhanced mobs. A quiet retreat and a controlled entrance matter.', 'Exposed light can be seen from far away. Light the approach and the working area, but do not assume a torch wall is a complete defence.', 'Give the base an inner room, a sightline, an alternate exit, and a way to close off the farm and workshop. Build a watchtower when the threat makes it useful.', 'Treat Better Dungeons as expeditions: bring food, blocks, light, a way home, and a point at which turning back is sensible.'] },
  { n: '04', title: 'Read the world before extracting it', image: photos.wildlife, mods: 'Naturalist', source: 'https://modrinth.com/mod/naturalist', intro: 'Naturalist adds animals, variants, drops, and behaviour that make biomes worth observing. It is an atmosphere and interaction layer, not a population simulator or a reason to kill everything nearby.', steps: ['Watch animals in their biome before deciding what belongs in a pen. Some are tameable or useful; others are scenery, food, or hazards.', 'Bring breeding stock home deliberately and leave wild habitats intact. A settlement feels more self-sufficient when it does not empty the surrounding landscape.', 'Keep a field notebook or signs for notable species, safe water, dangerous approaches, and useful routes.', 'If a creature behaves unexpectedly, test it in a safe enclosure first; do not assume every animal has the same rules.'] },
  { n: '05', title: 'Turn terrain into infrastructure', image: photos.terralith, mods: 'Terralith + Tectonic + Gliding', source: 'https://modrinth.com/mod/terralith', intro: 'The world-generation mods make geography consequential. The useful question is not “where is the best seed?” but “what route and settlement does this place support?”', steps: ['On the first trip, find water, food, a defensible approach, and at least two routes outward. Mark the return route.', 'Build small wayfinding objects—signposts, towers, camp shelters, bridges—before trying to flatten the landscape.', 'Gliding turns height into transport. Save it for a planned expedition and treat launch points as shared infrastructure.', 'Keep a second outpost or supply cache before a long dungeon, ocean, mountain, or Nether trip.'] },
  { n: '06', title: 'Make the settlement legible', image: photos.building, mods: 'Supplementaries + Handcrafted + Tom’s Simple Storage', source: 'https://modrinth.com/mod/supplementaries', intro: 'A self-sufficient base is a set of readable work areas, not a chest maze. Decoration helps because it gives each system a place and a memory.', steps: ['Build in this order: pantry and farm, defended entrance, workshop, storage room, map/wayfinding wall, then specialised rooms.', 'Supplementaries supplies signposts, jars, ropes, planters, lights, and small mechanisms. Handcrafted supplies furniture and visual distinctions. Use JEI for any specific item.', 'Start Tom’s Simple Storage with one terminal and a small connected set of inventories. Expand only when you know what is missing; label inputs and outputs.', 'Keep raw materials, food, tools, and project supplies visibly separate even after they are searchable. The network should reduce friction, not erase shared understanding.'] },
  { n: '07', title: 'Graduate from chores', image: photos.automation, mods: "CC: Tweaked + Oritech", source: 'https://tweaked.cc/module/turtle.html', intro: 'Automation is the second half of the pack. First make work reliable; then make it repeatable; only then make it large.', steps: ['A turtle needs fuel to move. If it stops, check fuel, inventory space, the block in front, and whether the program checked the function’s false/error result.', 'Start with a test lane and a boring job: move items, replant a small tree row, or dig a short marked tunnel. Give the turtle a name and a stop procedure.', 'Use the built-in ComputerCraft help and JEI rather than searching for every recipe. The official turtle API covers movement, digging, placing, inventory, fuel, and upgrades.', 'Use Oritech to remove a material bottleneck. Build one generator, one processing chain, and one output store; do not build a factory whose inputs nobody can explain.', 'An automation is ready for the shared world when both players can answer: what does it consume, where does output go, how do we stop it, and what happens when it fails?'] },
];

const modRows = [
  ['Lookup', 'JEI', 'Recipe and use lookup. Press R for recipes, U for uses, and search by name or @mod.'],
  ['Food', 'NutritionZ', 'Tracks nutrient variety; rotate meals rather than living on one crop.'],
  ['Food', "Farmer's Delight", 'A kitchen loop built around crops, a Cutting Board, a Cooking Pot, and meals.'],
  ['Danger', 'Zombie Awareness', 'Enhanced mobs investigate blood, sound, and exposed light.'],
  ['World', 'Naturalist', 'Animals, variants, drops, and biome-specific behaviour.'],
  ['World', 'Terralith + Tectonic', 'Large terrain and biome changes; routes and settlement sites matter.'],
  ['Travel', 'Gliding', 'Makes cliffs, towers, launch points, and high routes useful.'],
  ['Explore', "YUNG's Better Dungeons", 'Larger dungeon expeditions that need supplies and an exit plan.'],
  ['Build', 'Supplementaries + Handcrafted', 'Settlement details, signs, ropes, lights, furniture, and useful small objects.'],
  ['Carry', "Traveler's Backpack", 'Portable storage, sleeping bag, upgrades, and fluid tanks.'],
  ['Logistics', "Tom's Simple Storage", 'One searchable terminal over connected inventories.'],
  ['Automation', 'CC: Tweaked', 'Lua computers, turtles, peripherals, and programmable labour.'],
  ['Automation', 'Oritech', 'Power, processing, machines, and later industrial scale.'],
];

const milestones = [
  ['01', 'Food independence', 'A mixed field, dependable animal or crop sources, emergency food, and enough meal variety for both players.'],
  ['02', 'A defensible home', 'A controlled entrance, sightlines, inner retreat, alternate exit, and a perimeter that responds to actual problems.'],
  ['03', 'Material independence', 'A renewable tree/crop area, organised raw materials, and marked expeditions for anything not yet renewable.'],
  ['04', 'Logistics independence', 'A searchable Tom’s Storage terminal, labelled inputs and outputs, and a workshop where projects can be resumed.'],
  ['05', 'Labour independence', 'A turtle can perform one small job safely, report failure, and be stopped without destroying the settlement.'],
  ['06', 'Industrial independence', 'Oritech handles a real bottleneck, with power, processing, output, and maintenance understood by both players.'],
];

export default function Home() {
  return <main>
    <nav className="nav" aria-label="Primary navigation"><a className="brand" href="#top"><span>✦</span> OPEN-AIR SETTLEMENT</a><div className="navlinks"><a href="#start">Start here</a><a href="#systems">Systems</a><a href="#milestones">Milestones</a><a href="#setup">Join</a></div></nav>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">PRACTICAL REFERENCE / FABRIC 1.21.1 / PACK 1.0.4</p><h1>How to become<br /><em>self-sufficient.</em></h1><p className="lede">A working guide for two players: what to prioritise, what each system is for, and where to look in-game when a detail matters.</p><div className="hero-actions"><a className="button primary" href="#start">Start here <span>↓</span></a><a className="button quiet" href="#systems">See systems</a></div></div><div className="hero-images" aria-label="Scenes from included mods"><img className="hero-main" src={photos.terralith} alt="Terralith terrain" /><img className="hero-small top" src={photos.wildlife} alt="Naturalist wildlife" /><img className="hero-small bottom" src={photos.automation} alt="Oritech machinery" /><div className="image-caption">No recipe memorisation required.<br />Use JEI when you need it.</div></div></section>
    <section className="manifesto"><p><strong>How to use this page:</strong> read the first-week plan and the milestone ladder once. During play, return to the system that is currently causing friction. Recipes, item uses, and exact machine layouts belong in JEI or the relevant in-game guide.</p></section>
    <section className="week" id="start"><div className="section-heading"><p className="eyebrow">FIRST THREE SESSIONS</p><h2>A route through the early game</h2></div><div className="week-grid"><article><span>SESSION 1</span><h3>Stay alive and map the problem</h3><p>Secure temporary shelter, mixed food, a retreat, and a route to water. Do not spend the whole session building a permanent house.</p></article><article><span>SESSION 2</span><h3>Make food and night predictable</h3><p>Start the mixed plot, establish a small pantry, test the base entrance, and learn what noise and light attract.</p></article><article><span>SESSION 3</span><h3>Make the settlement useful</h3><p>Choose rooms, connect storage, mark routes, and pick one repeated chore that should eventually become a turtle or machine job.</p></article><article><span>EVERY SESSION</span><h3>Leave a better memory</h3><p>Add a sign, map mark, supply cache, path, or labelled chest. The settlement should remember what the two of you learned.</p></article></div></section>
    <section className="guide" aria-label="Practical system guides">{guides.map((guide) => <article className="guide-card" key={guide.n}><div className="card-art"><img src={guide.image} alt="" /><span>{guide.n}</span></div><div className="card-copy"><p className="eyebrow">{guide.mods}</p><h2>{guide.title}</h2><p>{guide.intro}</p><ol>{guide.steps.map((step) => <li key={step}>{step}</li>)}</ol><a href={guide.source} target="_blank" rel="noreferrer">Optional deeper reference <span>↗</span></a></div></article>)}</section>
    <section className="mod-index" id="systems"><div className="section-heading"><p className="eyebrow">SYSTEMS AT A GLANCE</p><h2>What to reach for when something is hard</h2><p>Supporting libraries and performance mods are intentionally omitted here. If a system is not in this table, it probably does not need your attention during play.</p></div><div className="mod-table">{modRows.map(([kind, name, description]) => <div className="mod-row" key={name}><span>{kind}</span><strong>{name}</strong><p>{description}</p></div>)}</div></section>
    <section className="week" id="milestones"><div className="section-heading"><p className="eyebrow">SELF-SUFFICIENCY LADDER</p><h2>Use these as shared project markers</h2></div><div className="week-grid">{milestones.map(([number, title, description]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="setup" id="setup"><div><p className="eyebrow">INSTALLATION &amp; MULTIPLAYER</p><h2>Keep the shared world compatible.</h2></div><div className="setup-list"><article><span>01</span><h3>Use the 1.0.4 pack</h3><p>Import the shared CurseForge zip, use Java 21, and launch Open-Air Settlement. Gameplay mods must match the server; shaders and other visual settings may differ.</p></article><article><span>02</span><h3>Connect on LAN</h3><p>Use the host computer’s current local IP address and port 25565. If it is absent from the LAN list, use Direct Connection.</p></article><article><span>03</span><h3>Do not repair one jar at a time</h3><p>Keep Iris 1.8.8 with Sodium 0.6.13 and Supplementaries 3.6.7. Do not re-add Realistic Wildlife; it caused severe server tick stalls.</p></article></div></section>
    <section className="references"><p className="eyebrow">OPTIONAL SOURCE SHELF</p><p className="source-note">The guide above is meant to stand on its own. These are the source pages to consult only when the in-game interface or this guide does not answer a specific question.</p><div className="reference-links"><a href="https://modrinth.com/mod/jei" target="_blank" rel="noreferrer">JEI</a><a href="https://modrinth.com/mod/naturalist" target="_blank" rel="noreferrer">Naturalist</a><a href="https://modrinth.com/mod/zombie-awareness" target="_blank" rel="noreferrer">Zombie Awareness</a><a href="https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated" target="_blank" rel="noreferrer">Farmer&apos;s Delight</a><a href="https://tweaked.cc/module/turtle.html" target="_blank" rel="noreferrer">CC: Tweaked turtles</a><a href="https://modrinth.com/mod/supplementaries" target="_blank" rel="noreferrer">Supplementaries</a><a href="https://modrinth.com/mod/oritech" target="_blank" rel="noreferrer">Oritech</a></div></section>
    <footer>OPEN-AIR SETTLEMENT <span>•</span> PRACTICAL REFERENCE / PACK 1.0.4</footer>
  </main>;
}
