name = "Open-Air Settlement"
author = "Nicky and Benji"
version = "1.0.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3edcd386f94987ec77acf6e723ead60428c7f8fcc390c04e55341f5d8223c84"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
