name = "Open-Air Settlement"
author = "Nicky and Benji"
version = "1.0.35"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "765b4def6b57c708a43005528f81ea3eb0328ab896a97726beaab4225f8f21ca"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
