name = "Open-Air Settlement"
author = "Nicky and Benji"
version = "1.0.48"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26b042c8420b369b0544990621cca9a1c71dcdec5107d5502f32cfac01b8e168"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
